spring.application.name=api-java
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

server.port=8080