spring.application.name=admin-jsf

# Porta diferente do api-java (8080) e do apps/web (3000)
server.port=8081

# Modo de desenvolvimento do JSF: mensagens de erro mais detalhadas
joinfaces.faces.project-stage=Development

# Tema visual do PrimeFaces
joinfaces.faces.primefaces.theme=saga