spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.swiifhnlijjqbbctzjsy
spring.datasource.password=AZKN3qN2KxHWBqDG
spring.datasource.hikari.data-source-properties.prepareThreshold=0






